version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/notesapp
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: src/frontend/note-app/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: