services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend/note-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=notesapp
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongodb_data: